name: BriskUp
favicon: null
layout_spectrum: 0.4991
typography_spectrum: 0.52958
title: 'BriskUp '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5e2d85'
    - '#000000'
    - '#d29c29'
    - '#fbd15c'
    - '#0000ff'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.801507749594748
purpose: []
